import { getDocuments } from "@/utils/firestore";
import Hero from "./components/Hero";
export const revalidate = 0;

export const metadata = {
  title: "vjoy-landing",
  description: "Generated by create next app",
};

export default async function Page() {
  const docs = await getDocuments("signups");

  return <Hero docs={docs.result} />;
}
